import { useState, useEffect } from 'react';
import { FileText, Download, RefreshCw, BookOpen } from 'lucide-react';
import Sidebar from '../components/Sidebar';
import { documentsAPI, summaryAPI } from '../api/axios';
import './Summary.css';

export default function SummaryPage() {
  const [documents, setDocuments] = useState([]);
  const [selectedDoc, setSelectedDoc] = useState('');
  const [summaryText, setSummaryText] = useState('');
  const [loading, setLoading] = useState(false);

  // 1. Documents mangwa lo
  useEffect(() => {
    const fetchDocs = async () => {
      try {
        const res = await documentsAPI.getAll();
        setDocuments(res.data);
        if (res.data.length > 0) {
          setSelectedDoc(res.data[0]._id);
        }
      } catch (error) {
        console.error("Doc fetch error", error);
      }
    };
    fetchDocs();
  }, []);

  // 2. Summary generate karwao Python AI Engine se
  const generateSummary = async () => {
    if (!selectedDoc) return;
    setLoading(true);
    setSummaryText('');
    try {
      // Backend automatically fast summary nikalega
      const res = await summaryAPI.generate(selectedDoc);
      // Python output deta hai: res.data.summary 
      setSummaryText(res.data.summary || "No summary could be generated by AI.");
    } catch (error) {
      console.error("Summary Generation Error", error);
      setSummaryText("Failed to generate summary. Please check backend connection.");
    } finally {
      setLoading(false);
    }
  };

    // Naya function: Text ko file banakar browser me download karwane ke liye
  const handleDownload = () => {
    if (!summaryText) return; // Agar text khali hai to kuch na kare
    
    // Summary Text ko ek actual ".txt" File data format me badalna
    const blob = new Blob([summaryText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    
    // Background me download link banake uspar auto-click karwana
    const a = document.createElement('a');
    a.href = url;
    a.download = `AI_Summary_${activeDocName.replace('.pdf', '')}.txt`; 
    document.body.appendChild(a);
    a.click();
    
    // Safai karna (memory bachaane ke liye)
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };


  // Jab page khule to default pehli file ka summary generate ho jaye (optional)
  useEffect(() => {
    if (selectedDoc && !summaryText && !loading) {
      generateSummary();
    }
  // eslint-disable-next-line
  }, [selectedDoc]);

  const activeDocName = documents.find(d => d._id === selectedDoc)?.title || 'No file selected';

  return (
    <div className="app-layout">
      <Sidebar />
      <main className="main-content">
        <div className="summary-header animate-fade-in">
          <div>
            <h1 className="page-title">Document Summary</h1>
            <p className="page-subtitle">AI-generated overview</p>
          </div>
          <div className="summary-actions">
            <select 
                className="input-field" 
                value={selectedDoc} 
                onChange={(e) => setSelectedDoc(e.target.value)}
                style={{ width: '250px', cursor: 'pointer', marginRight: '10px' }}
            >
                {documents.length > 0 ? (
                    documents.map(d => <option key={d._id} value={d._id}>{d.title}</option>)
                ) : (
                    <option value="">No PDF Uploaded Yet</option>
                )}
            </select>

            <button className="outline-btn summary-action-btn" onClick={generateSummary} disabled={loading || !selectedDoc}>
              <RefreshCw size={16} className={loading ? "spin" : ""} /> {loading ? "Generating..." : "Generate New"}
            </button>
            <button className="gradient-btn summary-action-btn" onClick={handleDownload} disabled={!summaryText}>
              <Download size={16} /> Download Text File
            </button>

          </div>
        </div>

        <div className="summary-badge-row" style={{ marginTop: '20px' }}>
          <span className="badge badge-info">
            <BookOpen size={12} style={{ marginRight: 4 }} /> {activeDocName}
          </span>
        </div>

        {/* Clean and Professional Summary Output Area */}
        <div className="summary-sections" style={{ marginTop: '20px' }}>
          <div className="summary-card glass-card" style={{ padding: '30px' }}>
            <div className="summary-card-header">
              <FileText size={20} className="summary-card-icon" />
              <h3>AI Legal Overview</h3>
            </div>
            
            {loading ? (
                <div style={{ padding: '40px', textAlign: 'center', color: 'var(--text-secondary)' }}>
                    <p className="pulse">AI engine is reading the entire document safely... please wait 🤖</p>
                </div>
            ) : summaryText ? (
                <p className="summary-card-text" style={{ fontSize: '1.1rem', lineHeight: '1.8', whiteSpace: 'pre-wrap' }}>
                    {summaryText}
                </p>
            ) : (
                <p style={{ color: 'var(--text-secondary)' }}>Select a document and click Generate.</p>
            )}

          </div>
        </div>
      </main>
    </div>
  );
}
